apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  tagPolicy:
    gitCommit:
      ignoreChanges: false
  artifacts:
    - image: elianrivoira/auth
      context: auth
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/client
      context: client
      sync:
        manual:
          - src: .
            dest: '**/*.js'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/tickets
      context: tickets
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/orders
      context: orders
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: elianrivoira/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
