apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  artifacts:
    - image: elianrivoira/auth
      context: auth
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/client
      context: client
      sync:
        manual:
          - src: .
            dest: '**/*.js'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/tickets
      context: tickets
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
    - image: elianrivoira/orders
      context: orders
      sync:
        manual:
          - src: .
            dest: 'src/**/*.ts'
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
